<?php
/**
 * Larfree Api类
 * @author blues
 */
namespace App\Http\Controllers\Admin\Common;
use App\Repositories\User\UserRepository;
use Illuminate\Http\Request;
use Larfree\Controllers\AdminApisController as Controller;
class UserController extends Controller
{
    public $in=[
        'index'=>[
            'phone'=>[
              'rule'=>['sometimes'],
            ],
        ],
    ];
    public function __construct(UserRepository $repository)
    {
        $this->repository = $repository;
        parent::__construct();
    }
    public function show($id, Request $request)
    {
        if($id == 0){
            $id = getLoginUserID();
        }
        return parent::show($id, $request); // TODO: Change the autogenerated stub
    }

}
