<?php
/**
 * Larfree Api类
 * @author blues
 */

namespace App\Http\Controllers\Api\Test;

use App\Models\Test\TestTest;
use App\UserController;
use Iblues\AnnotationTestUnit\Annotation as ATU;
use Illuminate\Http\Request;
use Larfree\Controllers\ApisController as Controller;
use App\Repositories\Test\TestTestRepository;
use App\Services\Test\TestTestService;
use OpenApi\Annotations as OA;

class TestController extends Controller
{
    public function __construct(TestTestService $service)
    {
        $this->service = $service;
        parent::__construct();
    }

    /**
     * @param Request $request
     * @return mixed
     * @throws \Exception
     * @author Blues
     * @ATU\Api(
     *     @ATU\Request(),
     *     @ATU\Response(200,{
     *      "code":true,
     *      "data":{{"id":true,"user":true}}
     *     }),
     * )
     *
     *
     * @ATU\Api(
     *     @ATU\Response({
     *      "data":true,"status":1
     *     }),
     * )
     *
     * @ATU\Api(
     *     title="测试标题",
     * )
     *
     * 验证权限中间件
     * @ATU\Api(
     *     @ATU\Login(false),
     *     @ATU\Response(401),
     * )
     */
    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @param Request $request
     * @return \Illuminate\Database\Eloquent\Model
     * @throws \Exception
     * @author Blues
     * @ATU\Api(
     *     path=@ATU\GetParam("TestTest.id"),
     *     @ATU\Before("create",{TestTest::class,{"title":"测试"} }),
     *     @ATU\Response({
     *      "status":1,
     *      "data":{"title":@ATU\GetParam("TestTest.title")},
     *     }),
     *     @ATU\Assert("assertDatabaseHas",{"test_test",{"title":@ATU\GetParam("TestTest.title")} }),
     * )
     *
     * @ATU\Api(
     *     path="latest"
     * )
     */
    public function show($id, Request $request)
    {
        return parent::show($id, $request); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request $request
     * @return mixed
     * @throws \Exception
     * @author Blues
     * @ATU\Api(
     *     @ATU\Before("create",{TestTest::class,{"title":"测试22"} }),
     *     @ATU\Request({"title":@ATU\GetParam("TestTest.title"),"content":@ATU\GetParam("TestTest.title"),"user_id":"123"}),
     *     @ATU\Response({
     *        "data":{"id":true,"title":@ATU\GetRequest("title")}
     *       },
     *       @ATU\Assert("assertSee",{@ATU\GetParam("TestTest.title")}),
     *       @ATU\Assert("assertSee",{@ATU\GetRequest("title")}),
     *       @ATU\Assert("assertJson", {{"data":@ATU\GetRequest}} ),
     *       @ATU\Assert("assertOk"),
     *     ),
     *     @ATU\Assert("assertDatabaseHas",{"test_test",{"id":1}} ),
     *     @ATU\Assert("assertDatabaseHas",{"test_test",@ATU\GetRequest()} ),
     *     @ATU\Assert("assertDatabaseHas",{"test_test",
     *      { "title" : @ATU\GetResponse("data.title") }
     *     }),
     * ),
     *
     * @ATU\Api(
     *     @ATU\Request({"title":1}),
     *     @ATU\Response(422,{
     *      "data":{"title":true}
     *     })
     * )
     */
    public function store(Request $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request $request
     * @param $id
     * @return mixed
     * @throws \Exception
     * @author Blues
     * @ATU\Api(
     *     path="latest",
     *     @ATU\Response(),
     * )
     * @ATU\Api(
     *     path="latest",
     *     @ATU\Request({"title":333}),
     * )
     */
    public function update(Request $request, $id)
    {
        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @param Request $request
     * @return string|void
     * @throws \Exception
     * @author Blues
     *
     * @ATU\Api(
     *    title="删除测试",
     *    path="1",
     *    @ATU\Assert("assertDatabaseMissing",{"test_test",{"id":1}})
     * )
     */
    public function destroy($id, Request $request)
    {
        return parent::destroy($id, $request); // TODO: Change the autogenerated stub
    }
}
