<?php
/**
 * Larfree Api类
 * @author blues
 * @see Larfree\Controllers\ApisController
 */
namespace App\Http\Controllers\Admin\Test;

use App\Models\Test\TestTest;
use Illuminate\Http\Request;
use Larfree\Controllers\AdminApisController as Controller;

//use AdminApiController as Controller;


class TestController extends Controller
{

    public $in=[
        'index'=>[
            'get'=>[
                'name'=>'测试',
                'rule'=>['required'],
            ],
            'select'=>[
                'rule'=>['required'],
            ],
        ],
        'update'=>[
            '*',
            'datetime'=>[
                'name'=>'日期',
                'rule'=>['required','date'],
            ],
            'select'=>[
                'rule'=>['required'],
            ],
            'title3',
        ],
        'store'=>[
            '*',
            'datetime'=>[
                'name'=>'日期',
                'rule'=>['required','date'],
            ],
            'select'=>[
                'rule'=>['required'],
            ],
            'title3'=>false,
        ]
    ];


    public function __construct(TestTest $model )
    {
        $this->model = $model;
        parent::__construct();
    }

    /**
     * @OA\Get(
     *   summary="测试接口",
     *   description="获取大批量信息",
     *   path="/test/test_detail/",
     *   tags={"测试组"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="其他描述 md5:ff1e9342bd0dc30d4ad08c852b2693fe",
     *   ),
     * )
     */
    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }
}