<?php
/**
 * Larfree Api类
 * @author blues
 * @see Larfree\Controllers\ApisController
 */
namespace App\Http\Controllers\Admin\Test;

use App\Models\Test\TestTest;
use Illuminate\Http\Request;
use Larfree\Controllers\AdminApisController as Controller;

//use AdminApiController as Controller;


class TestController extends Controller
{

    public $in=[
        'index'=>[
            'get'=>[
                'name'=>'测试',
                'rule'=>['required'],
            ],
            'select'=>[
                'rule'=>['required'],
            ],
        ],
        'show'=>[
            'id',
        ],
        'update'=>[
            'datetime'=>[
                'name'=>'日期',
                'rule'=>['required','date'],
            ],
            'select'=>[
                'rule'=>['required'],
            ],
            'title',
        ],
        'store'=>[
            'select'=>false,
            'created_at'=>false,
            'updated_at'=>false,
        ]
    ];


    public function __construct(TestTest $model )
    {
        $this->model = $model;
        parent::__construct();
    }

    /**
     * @OA\Put(
     *   summary="修改数据",
     *   description="修改数据",
     *   path="/test/test/{id}",
     *   tags={"测试组"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="其他描述 md5:ff1e9342bd0dc30d4ad08c852b2693fe",
     *   ),
     * )
     */
    public function update(Request $request, $id)
    {
        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\Get(
     *   summary="测试接口2",
     *   description="获取大批量信息",
     *   path="/test/test/",
     *   tags={"测试组"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="其他描述 md5:ff1e9342bd0dc30d4ad08c852b2693fe",
     *   ),
     *
     *     @OA\Parameter(
     *         name="test",
     *         in="path",
     *         description="注释中额外定义的参数",
     *         schema={"type":"integer"},
     *         examples="123",
     *     ),
     * )
     */
    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }


    /**
     * @OA\Get(
     *   summary="读取单个文件",
     *   description="读取单个文件",
     *   path="/test/test/{id}",
     *   tags={"测试组"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="其他描述 md5:ff1e9342bd0dc30d4ad08c852b2693fe",
     *   ),
     * )
     */
    public function show($id, Request $request)
    {
        return parent::show($id, $request); // TODO: Change the autogenerated stub
    }



    /**
     * @OA\Post(
     *   summary="添加数据",
     *   description="添加post",
     *   path="/test/test",
     *   tags={"测试组"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="其他描述 md5:ff1e9342bd0dc30d4ad08c852b2693fe",
     *   ),
     * )
     */
    public function store(Request $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }



}