<?php
/**
 * Larfree Api类
 * @author blues
 */
namespace App\Http\Controllers\Admin\Test;

use App\Models\Test\TestTestDetail;
use Illuminate\Http\Request;

use Larfree\Controllers\AdminApisController as Controller;
use App\Models\Test\TestDetail;
class TestDetailController extends Controller
{

    public $in=[
        'index'=>[
            '*',
            'datetime'=>[
                'name'=>'单独定义的参数',
                'rule'=>['required','date'],
            ],
        ],
        'update'=>[
            '*',
            'datetime'=>[
                'name'=>'日期',
                'rule'=>['required','date'],
            ],
            'select'=>[
                'rule'=>['required'],
            ],
            'title3',
        ],
        'store'=>[
            '*',
            'datetime'=>[
                'name'=>'日期',
                'rule'=>['required','date'],
            ],
            'select'=>[
                'rule'=>['required'],
            ],
            'title3'=>false,
        ]
    ];

    public function __construct(TestTestDetail $model )
    {
        $this->model = $model;
        parent::__construct();
    }

    /**
     * @OA\Get(
     *   summary="测试接口",
     *   description="获取大批量信息",
     *   path="/test/test_detail/",
     *   tags={"测试组"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="其他描述 md5:ff1e9342bd0dc30d4ad08c852b2693fe",
     *   ),
     * )
     */
    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }
}