<?php
/**
 * Larfree Api类
 * @author blues
 */
namespace App\Http\Controllers\Api\Common;
use App\Models\Common\CommonUser;
use App\Repositories\Test\NavRepository;
use Illuminate\Http\Request;

use Larfree\Controllers\ApisController as Controller;
class UserController extends Controller
{
    public $in=[
        'index'=>[
            'phone'=>[
                'rule'=>['sometimes'],
            ],
        ],
    ];
    public function __construct(NavRepository $repository)
    {
        $this->repository = $repository;
        parent::__construct();
    }
    public function show($id, Request $request)
    {
        if($id == 0){
            $id = getLoginUserID();
        }
        return parent::show($id, $request); // TODO: Change the autogenerated stub
    }
}
